# Generated by Django 5.1.1 on 2024-10-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('offer_type', models.CharField(choices=[('EDUCATION', 'Education'), ('WORK', 'Work')], max_length=10)),
                ('category', models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid')], max_length=4)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
