# Generated by Django 5.1.1 on 2024-10-02 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WORK', 'Work'), ('EDUCATION', 'Education')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('full_scholarship', models.BooleanField(default=False)),
                ('ed_level', models.CharField(blank=True, max_length=255, null=True)),
                ('is_paid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField(blank=True, null=True)),
                ('high_school_name', models.CharField(max_length=255)),
                ('high_school_address', models.CharField(max_length=255)),
                ('high_school_graduation_date', models.DateField()),
                ('high_school_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('high_school_major_subjects', models.TextField()),
                ('high_school_honors_awards', models.TextField(blank=True, null=True)),
                ('undergraduate_university_name', models.CharField(max_length=255)),
                ('undergraduate_university_address', models.CharField(max_length=255)),
                ('undergraduate_graduation_date', models.DateField()),
                ('undergraduate_degree_awarded', models.CharField(max_length=255)),
                ('undergraduate_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('undergraduate_major_subjects', models.TextField()),
                ('undergraduate_honors_awards', models.TextField(blank=True, null=True)),
                ('recommender1_name', models.CharField(max_length=255)),
                ('recommender1_title_position', models.CharField(max_length=255)),
                ('recommender1_institution_organization', models.CharField(max_length=255)),
                ('recommender1_email', models.EmailField(max_length=254)),
                ('recommender1_phone_number', models.CharField(max_length=20)),
                ('recommender2_name', models.CharField(max_length=255)),
                ('recommender2_title_position', models.CharField(max_length=255)),
                ('recommender2_institution_organization', models.CharField(max_length=255)),
                ('recommender2_email', models.EmailField(max_length=254)),
                ('recommender2_phone_number', models.CharField(max_length=20)),
                ('recommender3_name', models.CharField(max_length=255)),
                ('recommender3_title_position', models.CharField(max_length=255)),
                ('recommender3_institution_organization', models.CharField(max_length=255)),
                ('recommender3_email', models.EmailField(max_length=254)),
                ('recommender3_phone_number', models.CharField(max_length=20)),
                ('background_influences', models.TextField()),
                ('academic_interests', models.TextField()),
                ('career_goals', models.TextField()),
                ('extracurricular_activities', models.TextField()),
                ('personal_achievements', models.TextField()),
                ('challenges_overcoming', models.TextField()),
                ('unique_qualities', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('sat_act_scores', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('gre_gmat_scores', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('toefl_ielts_scores', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('certificates_awards', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('passport_id_scan', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('highschool_transcript', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('highschool_diploma', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('national_exam_result', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('university_transcripts', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('university_degree', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('work_experience', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('passport_size_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='myapp.offers')),
            ],
        ),
    ]
