# Generated by Django 5.1.1 on 2024-10-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers_images/'),
        ),
        migrations.AddField(
            model_name='offers',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
