# Generated by Django 5.1.1 on 2024-10-08 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_offers_image_offers_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat_act_scores', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('gre_gmat_scores', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('toefl_ielts_scores', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('certificates_awards', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('passport_id_scan', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('highschool_transcript', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('highschool_diploma', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('national_exam_result', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('university_transcripts', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('university_degree', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('work_experience', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('passport_size_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school_name', models.CharField(max_length=255)),
                ('high_school_address', models.CharField(max_length=255)),
                ('high_school_graduation_date', models.DateField()),
                ('high_school_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('high_school_major_subjects', models.TextField()),
                ('high_school_honors_awards', models.TextField(blank=True, null=True)),
                ('undergraduate_university_name', models.CharField(max_length=255)),
                ('undergraduate_university_address', models.CharField(max_length=255)),
                ('undergraduate_graduation_date', models.DateField()),
                ('undergraduate_degree_awarded', models.CharField(max_length=255)),
                ('undergraduate_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('undergraduate_major_subjects', models.TextField()),
                ('undergraduate_honors_awards', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalStatementsEssays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_influences', models.TextField()),
                ('academic_interests', models.TextField()),
                ('career_goals', models.TextField()),
                ('extracurricular_activities', models.TextField()),
                ('personal_achievements', models.TextField()),
                ('challenges_overcoming', models.TextField()),
                ('unique_qualities', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title_position', models.CharField(max_length=255)),
                ('institution_organization', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='academic_interests',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='background_influences',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='career_goals',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='certificates_awards',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='challenges_overcoming',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='extracurricular_activities',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='gre_gmat_scores',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='high_school_address',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='high_school_gpa',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='high_school_graduation_date',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='high_school_honors_awards',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='high_school_major_subjects',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='high_school_name',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='highschool_diploma',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='highschool_transcript',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='national_exam_result',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='passport_id_scan',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='passport_size_photo',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='personal_achievements',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender1_email',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender1_institution_organization',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender1_name',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender1_phone_number',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender1_title_position',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender2_email',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender2_institution_organization',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender2_name',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender2_phone_number',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender2_title_position',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender3_email',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender3_institution_organization',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender3_name',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender3_phone_number',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='recommender3_title_position',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='sat_act_scores',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='toefl_ielts_scores',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='undergraduate_degree_awarded',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='undergraduate_gpa',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='undergraduate_graduation_date',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='undergraduate_honors_awards',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='undergraduate_major_subjects',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='undergraduate_university_address',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='undergraduate_university_name',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='unique_qualities',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='university_degree',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='university_transcripts',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='contact_information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.contactinformation'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='documents_required',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.documentsrequired'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='educational_background',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.educationalbackground'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='personal_information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.personalinformation'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='personal_statements_essays',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.personalstatementsessays'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='recommender1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommender1', to='myapp.recommender'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='recommender2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommender2', to='myapp.recommender'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='recommender3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommender3', to='myapp.recommender'),
        ),
    ]
